-- MySQL Script generated by MySQL Workbench
-- Mon Oct 23 18:38:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema x9academico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema x9academico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `x9academico` DEFAULT CHARACTER SET latin1 ;
USE `x9academico` ;

-- -----------------------------------------------------
-- Table `x9academico`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `x9academico`.`endereco` (
  `idendereco` INT(11) NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) CHARACTER SET 'latin1' NOT NULL,
  `numeroend` INT(11) NOT NULL,
  `cidade` VARCHAR(45) CHARACTER SET 'latin1' NOT NULL,
  `UF` VARCHAR(2) CHARACTER SET 'latin1' NOT NULL,
  `cep` INT(8) NOT NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `x9academico`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `x9academico`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `DTYPE` VARCHAR(31) CHARACTER SET 'latin1' NOT NULL,
  `login` VARCHAR(100) CHARACTER SET 'latin1' NOT NULL,
  `senha` VARCHAR(255) CHARACTER SET 'latin1' NOT NULL,
  `tipousuarios` INT(11) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `telefone` INT(11) NOT NULL,
  `email` VARCHAR(70) CHARACTER SET 'latin1' NOT NULL,
  `nomecompleto` VARCHAR(60) CHARACTER SET 'latin1' NOT NULL,
  `endereco_idendereco` INT(11) NOT NULL,
  `rg` VARCHAR(9) CHARACTER SET 'latin1' NOT NULL,
  `data_nascimento` VARCHAR(10) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_1_idx` (`endereco_idendereco` ASC),
  CONSTRAINT `fk_usuario_1`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `x9academico`.`endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `x9academico`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `x9academico`.`administrador` (
  `idadministrador` INT(11) NOT NULL AUTO_INCREMENT,
  `cargo` VARCHAR(45) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`idadministrador`),
  CONSTRAINT `fk_administrador_1`
    FOREIGN KEY (`idadministrador`)
    REFERENCES `x9academico`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `x9academico`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `x9academico`.`turma` (
  `idturma` INT(11) NOT NULL AUTO_INCREMENT,
  `serie` VARCHAR(45) CHARACTER SET 'latin1' NOT NULL,
  `numerosala` INT(10) NULL DEFAULT NULL,
  `qtdAluno` INT(2) NOT NULL,
  PRIMARY KEY (`idturma`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `x9academico`.`responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `x9academico`.`responsavel` (
  `idresponsavel` INT(11) NOT NULL AUTO_INCREMENT,
  `parentesco` VARCHAR(45) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`idresponsavel`),
  CONSTRAINT `fk_responsavel_1`
    FOREIGN KEY (`idresponsavel`)
    REFERENCES `x9academico`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `x9academico`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `x9academico`.`aluno` (
  `idaluno` INT(11) NOT NULL AUTO_INCREMENT,
  `matricula` VARCHAR(45) CHARACTER SET 'latin1' NOT NULL,
  `nome` VARCHAR(45) CHARACTER SET 'latin1' NOT NULL,
  `turma_idturma` INT(11) NOT NULL,
  `data_nascimento` VARCHAR(45) CHARACTER SET 'latin1' NOT NULL,
  `deficiencia` VARCHAR(5) CHARACTER SET 'latin1' NOT NULL,
  `responsavel_idresponsavel` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idaluno`),
  INDEX `fk_aluno_1_idx` (`turma_idturma` ASC),
  INDEX `fk_aluno_2_idx` (`responsavel_idresponsavel` ASC),
  CONSTRAINT `fk_aluno_1`
    FOREIGN KEY (`turma_idturma`)
    REFERENCES `x9academico`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_2`
    FOREIGN KEY (`responsavel_idresponsavel`)
    REFERENCES `x9academico`.`responsavel` (`idresponsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `x9academico`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `x9academico`.`professor` (
  `idprofessor` INT(11) NOT NULL AUTO_INCREMENT,
  `idturma` INT(11) NOT NULL,
  PRIMARY KEY (`idprofessor`),
  INDEX `fk_professor_2_idx` (`idturma` ASC),
  CONSTRAINT `fk_professor_1`
    FOREIGN KEY (`idprofessor`)
    REFERENCES `x9academico`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professor_2`
    FOREIGN KEY (`idturma`)
    REFERENCES `x9academico`.`turma` (`idturma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `x9academico`.`relatorioparental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `x9academico`.`relatorioparental` (
  `idrelatorioparental` INT(11) NOT NULL AUTO_INCREMENT,
  `observacoes` VARCHAR(255) CHARACTER SET 'latin1' NULL DEFAULT NULL,
  `comportamento` FLOAT NULL DEFAULT NULL,
  `participacao_em_sala` FLOAT NULL DEFAULT NULL,
  `facilidade_com_disciplina` FLOAT NULL DEFAULT NULL,
  `trabalho_em_equipe` FLOAT NULL DEFAULT NULL,
  `lideranca` FLOAT NULL DEFAULT NULL,
  `motivacao` FLOAT NULL DEFAULT NULL,
  `criatividade` FLOAT NULL DEFAULT NULL,
  `aluno_idaluno` INT(11) NOT NULL,
  PRIMARY KEY (`idrelatorioparental`),
  INDEX `fk_relatorioparental_1_idx` (`aluno_idaluno` ASC),
  CONSTRAINT `fk_relatorioparental_1`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `x9academico`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
